db:
  mysql:
    image: mysql:8.1
    imagePullPolicy: Always
    listenPort: 3306
    volumeSize: 20Gi

  redis:
    image: redis:latest
    imagePullPolicy: Always
    listenPort: 6379
    volumeSize: 10Gi
