apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis-db-service
spec:
  selector:
    app: {{ .Release.Name }}-redis-db
  ports:
    - name: redis
      port: {{ .Values.db.redis.listenPort }}
      targetPort: {{ .Values.db.redis.listenPort }}
  externalTrafficPolicy: Local
  type: LoadBalancer
