apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mysql-config-cm
data:
  my.cnf: |-
    [mysqld]
    max_allowed_packet = 512M
    table_open_cache = 100
    innodb_lock_wait_timeout = 10
    wait_timeout = 28800
