apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-mysql-pv-claim
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mysql-db
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.mysql.volumeSize }}
