apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql-db-service
spec:
  selector:
    app: {{ .Release.Name }}-mysql-db
  ports:
    - name: mysql
      port: {{ .Values.db.mysql.listenPort }}
      targetPort: {{ .Values.db.mysql.listenPort }}
  externalTrafficPolicy: Local
  type: LoadBalancer
